- name: "PLAY - Déploiement images et conteneurs docker"
  hosts: srv01
  become: true

  pre_tasks:
    - name: Enregistrement de l'IP de srv01
      set_fact: 
        docker_host: "{{ ansible_facts['enp0s8']['ipv4']['address'] }}"

  roles:
    - docker_deploy

  tasks:
    - name: ip
      debug:
        msg: "{{ docker_host }}"
        verbosity: 1

    - name: Utilisation du module wait_for + option delegate_to
      wait_for:
        host: "{{ docker_host }}"
        port: 6379
      delegate_to: manager
    
    - name: "Utilisation du lineinfile + mode delegate_to pour modifier le fichier ansible.cfg sur maanager"
      lineinfile:
        path: "{{ playbook_dir }}/ansible.cfg"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^fact_caching =', line: "fact_caching = redis"}
        - { regexp: '^fact_caching_connection', line: "fact_caching_connection = {{ docker_host }}:6379" }
      delegate_to: manager