---
- name: "PLAY deploiement web apache"
  hosts: webservers
  become: true

  vars:
    appli_name: formation
    deploy_virtualhost: true
    #couleur: blue
  
  #pre_tasks:
  #  - name: "appel module set_fact pour surcharger variable couleur"
  #    set_fact:
  #      couleur: brown
  roles:
    - apache_0.0.1