all:
  children:
    linux:
      children:
        centos:
          hosts:
            srv03:
              ansible_python_interpreter: /usr/bin/python3
              ansible_ssh_host: 172.28.128.71
              key_status: absent
              password_strategy: always
              sudogrp: wheel
              var1: Serveurs Linux
        debian:
          vars:
            sudogrp: sudo
          hosts:
            srv01:
              ansible_python_interpreter: /usr/bin/python3
              ansible_ssh_host: 172.28.128.69
            srv02:
              ansible_python_interpreter: /usr/bin/python3
              ansible_ssh_host: 172.28.128.70
    ungrouped:
      hosts:
        manager:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    webservers:
      children:
        debian:
          hosts:
            srv01: {}
            srv02: {}
